In [11]:
import numpy as np

In [10]:
a = [1,2,3,4]
np.array(a).ndim

1

In [18]:
a = [[1,2,3,4],[5,6,7,8]]
print(np.array(a))
print(np.array(a).ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [17]:
a = [[1,2,4],[5,6,7,8]]
print(np.array(a))
print(np.array(a).ndim) # because of un-equal length

[list([1, 2, 4]) list([5, 6, 7, 8])]
1


In [15]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.ndim)


3


In [16]:
a = [[1,2,3,4],[5,6,7,8]]
np.array(a).shape

(2, 4)

In [19]:
a = [[1,2,3,4],[5,6,7,8]]
np.array(a).shape

(2, 4)

In [20]:
a = [[1,2,3,4],[5,6,7,8]]
np.array(a).dtype

dtype('int32')

In [21]:
a = [[1,2,3,4],[5,6,7,8]]
np.array(a).size

8

In [31]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
a = [[1,2,3,4],[5,6,7,8]]
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
np.ones_like((5,5))

array([1, 1])

In [45]:
a = [[1,2,3,4],[5,6,7,8]]
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
a = [[1,2,3,4],[5,6,7,8]]
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
a = [[1,2,3,4],[5,6,7,8]]
np.empty_like(a)

array([[-84891688,       403,   3801155,   5046364],
       [  5111873,   4587593,   5439557,   3014740]])

In [51]:
np.full((5,5),'Bilal')

array([['Bilal', 'Bilal', 'Bilal', 'Bilal', 'Bilal'],
       ['Bilal', 'Bilal', 'Bilal', 'Bilal', 'Bilal'],
       ['Bilal', 'Bilal', 'Bilal', 'Bilal', 'Bilal'],
       ['Bilal', 'Bilal', 'Bilal', 'Bilal', 'Bilal'],
       ['Bilal', 'Bilal', 'Bilal', 'Bilal', 'Bilal']], dtype='<U5')

In [59]:
a = [[1,2,3,4],[5,6,7,8]]
np.full_like(a,5.33)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [62]:
arr = np.arange(0,50,2)
print(arr)
arr1 = np.arange(100)
print(arr1)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [65]:
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [67]:
np.zeros((1,2,5)) # 1 array of 2 rows and 5 col

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [69]:
np.zeros((1,3,2,2,5))

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]])

In [77]:
a = np.array(np.arange(0,10))
print(a)
print(a[2:6])
a[2:6]=0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[0 1 0 0 0 0 6 7 8 9]


In [86]:
a = np.array(np.arange(0,10).reshape(5,2))
print(a)
print(a[1][0])
print(a[-1][-1])
print(a[1,0])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
2
9
2


In [87]:
arr = np.arange(6).reshape(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


In [89]:
print(arr.sum(0)) # here i have mentioned 0 which refer to rows and it means that for sum function my rows will collapse 
print(arr.sum(1)) # here i have mentioned 1 which refer to columns and it means that for sum function my columns will collapse 


[3 5 7]
[ 3 12]


In [108]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(arr2d)
print(arr2d[:2]) # selec first 2 rows
print(arr2d[:3]) # select first 3 rows
print(arr2d[:2,:2])
arr2d[1,:2]

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


array([4, 5])

In [122]:
# Similarly, I can select the third column but only the first two rows like so.
print(arr2d[:2,2])
print(arr2d[:,1])
print(arr2d[:-1]) # :-1 does not give all the rows but all-1 rowsin this case 3-1(start 2 rows)
print(arr2d[:-1,:-1])

[3 6]
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [128]:
a = np.ones((8,8))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [131]:
a = np.zeros((20,20))
# print(a)
var = 1
for i in range(len(a)): # 20
    a[i,i] = 1
    a[i,-var] = 1
    var += 1
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

In [146]:
a = np.zeros((20,20))
# print(a)
var = 1
a[0,0:20] = 1
a[:,0] = 1
a[19,0:-1] = 1
a[:,19] = 1
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [148]:
np.random.randn(5,5)

array([[ 0.77698807, -0.14059304, -0.96289723,  0.19271187, -0.23590886],
       [-0.19602401, -0.44960557, -1.37256194,  0.59044909,  0.37829212],
       [-1.29410248,  1.45559961,  1.44475988, -0.42067006, -0.14964877],
       [-0.97926353, -1.391138  , -1.03002681, -0.55414309, -1.54289388],
       [-1.52707195, -0.26433479, -0.08062288,  0.10125066, -0.31293638]])

In [150]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [155]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7,4)
print(data)
print(names == 'Bob') # since arthimetic operations in numpy applies on each and every element of an array and in this array
print(data[names == 'Bob']) # in this step what we've done is we have pasted/overlaped our boolean array(as index value) which we
# in this step what we've done is we have pasted/overlaped our boolean array(as index value) which we
# have created above, due to which whichever index(row) that has 'True' value will be replaced by the same index number in data array
# and rest of the index values wihch have 'False' will also be removed from data array.  
# so in boolean array only 0 and 3 has 'True' value so in data array only 0 and 3 
# index number will be left and others will be removed.
# passing boolean array as index is a method to paste/overlap data.

[[ 0.42263396 -1.82281102  0.66139781  0.96031088]
 [-0.37552543  1.11289485 -0.56682654  0.45634811]
 [-0.65755335 -0.55916067  0.39996268 -0.52771958]
 [-0.03590232 -0.35308841 -0.06717923  0.1831645 ]
 [ 0.82378509 -0.29395124  0.26135454 -0.74174245]
 [ 0.58464502  0.35064968 -1.79886919 -2.26548136]
 [-0.64639899  0.07262576 -2.92229449 -0.98935373]]
[ True False False  True False False False]
[[ 0.42263396 -1.82281102  0.66139781  0.96031088]
 [-0.03590232 -0.35308841 -0.06717923  0.1831645 ]]


In [157]:
data[~(names == 'Bob')] # ~ use as negative or not

array([[-0.37552543,  1.11289485, -0.56682654,  0.45634811],
       [-0.65755335, -0.55916067,  0.39996268, -0.52771958],
       [ 0.82378509, -0.29395124,  0.26135454, -0.74174245],
       [ 0.58464502,  0.35064968, -1.79886919, -2.26548136],
       [-0.64639899,  0.07262576, -2.92229449, -0.98935373]])

In [158]:
data[data>0]

array([0.42263396, 0.66139781, 0.96031088, 1.11289485, 0.45634811,
       0.39996268, 0.1831645 , 0.82378509, 0.26135454, 0.58464502,
       0.35064968, 0.07262576])

In [163]:
arr = np.empty((8, 4)) 
for i in range(8):
    arr[i] = i
print(arr)
print(arr[[0,2,4,6]])
# # we can use negetive indexing as well.
print(arr[[-8,-6,-4,-2]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [4. 4. 4. 4.]
 [6. 6. 6. 6.]]
[[0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [4. 4. 4. 4.]
 [6. 6. 6. 6.]]


In [172]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1, 5, 7, 2]])
print(arr[[1, 5, 7, 2],:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  5  6]
 [20 21 22]
 [28 29 30]
 [ 8  9 10]]


In [170]:
print(arr[[1, 5, 7, 2],[0,1,2,3]])
print(arr[[1, 5, 7, 2]][:,[3,0]])

[ 4 21 30 11]
[[ 7  4]
 [23 20]
 [31 28]
 [11  8]]


In [177]:
print(arr)
print(arr[[0,2,4,6],:][:,[0,1]])
print(arr[[0,2,4,6],:][:,[0,1]][1:3,1:])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1]
 [ 8  9]
 [16 17]
 [24 25]]
[[ 9]
 [17]]


In [180]:
a = np.array([[1, 2], [3, 4]]) # [1,2] has 0 index number while [3,4] has 1 index number
print(a)
print(a.transpose())
print(a.transpose((1, 0))) # here i changed the array indexes thats why their transpose is different 
print(a.transpose(0,1))


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [184]:
arr = np.arange(16).reshape((2, 2, 4)) # transpose will return (column,rows,how many of these arrays,,,,,) or 
# this will return (2,2,4)[::-1] = (4,2,2)
print(arr)
print(arr.transpose()) # this will return the transpose of reverse reshape value (4,2,2) 4 arrays of 2 rows and 2 column


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [186]:
arr = np.arange(16).reshape((2, 2, 4)) # here 2(axis) = 0(index number) , 2(axis) = 1(index number) , 4(axis) = 2(index number)
print(arr)
print(arr.swapaxes(1, 2))# what swapaxes does is it will swap the given axes and rearrange the values and reorder the array.
# print(arr.swapaxes(1, 2).shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [191]:
arr = np.arange(7)
print(np.exp(arr),end='\n\n') # this will calculate exponential of all elements (e**0 , e**1 , e**2 , e**3 ,....)

[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591  403.42879349]



In [192]:
x = np.random.randn(10)
print(x)
print(y)
y = np.random.randn(10)
print(np.maximum(x,y),end='\n\n')
# Here, numpy.maximum computed the element-wise maximum of the elements in x and y.



[-0.57421263  1.0085941   0.33344867 -1.02276148 -0.19687264 -1.42450653
  0.86698536 -0.80884896  0.31356822  0.8751777 ]
[-0.27043809  0.71000693  1.95882156  0.25952444 -1.81044847 -0.98882249
 -1.26710775  2.41950069  1.03845337 -0.14948792]
[-0.38813157  1.0085941   0.33344867  2.37561322 -0.19687264 -1.34437798
  0.86698536 -0.80884896  0.31356822  0.8751777 ]



In [195]:
a = np.zeros(7) # this is of same shape as square root array.
print(np.sqrt(arr,a)) # here i have saved my square root array in variable a which now is my square root array.
print(a)
print(arr) # still orignal array is not affected
# # we can also save the value in same array on which we have applied square root.


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974]
[0 1 2 3 4 5 6]


In [201]:
a = np.array([[1,2,np.nan],[np.nan,3,np.nan],[np.nan,np.nan,np.nan]])
print(a)
np.isnan(a)

[[ 1.  2. nan]
 [nan  3. nan]
 [nan nan nan]]


array([[False, False,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [8]:
print(np.eye(4))
print(np.eye(4,5))#### this is not a square matrix so the diagonal still will contain ones but due to an extra column it will skip that column
#### identity function's first parameter is 'n' which works for both rows as well as coloumn. 
print(np.identity(5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
from numpy.linalg import * # using asterisk(*) used to import all the functions available in the module.

In [14]:
arr = np.arange(4).reshape(2,2)
print(arr)
arr1 = np.arange(25).reshape(5,5)
print(arr1)

[[0 1]
 [2 3]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
print(det(arr))
print(det(arr1))

-2.0
0.0


In [17]:
arr1 = np.arange(25).reshape(5,5)
print(arr1)
print(np.diag(arr1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  6 12 18 24]


In [18]:
arr = np.array([2,4,6,8,10])
print(np.diag(arr))

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]


In [22]:
np.random.randn(5,5)

array([[ 0.69467108,  0.59336944, -0.96800871, -2.31108064,  1.41563047],
       [ 1.29328913,  2.15169799,  0.19798314, -0.08322397,  0.29110792],
       [-1.57962705, -1.76888113, -0.54327757, -0.32340679, -0.77983626],
       [ 2.70360743, -0.00789712,  0.86202499, -1.15396154, -1.56487724],
       [-0.94255339, -0.10233819,  0.90128291, -0.85000319, -0.83483557]])

In [71]:
np.random.seed(0) # here i initialized seed to 1
np.random.random(50)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])

In [73]:
# a = np.array([[1,2],[3,4]])
# b = np.array([[5,6]])
a = (2,2)
b = (1,2)
# axis= (0,1)
print(np.concatenate((a,b))) # here axis is 0 which means the array will concatenate along axis 0(which is concatenating 


[2 2 1 2]
